Update setup.py
added a change in line 40 "senaite.panic<1.2.0"
we get an error
Error: There is a version conflict.
We already have: senaite.lims 1.3.4
but senaite.panic 2.0.0 requires 'senaite.lims>=2.0.0rc1'