Fix Traceback "bika_widgets/remarks does not exist for ..." (#109)
This was because of https://github.com/senaite/senaite.core/pull/920

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 32, in _call
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 158, in render
  Module chameleon.zpt.template, line 297, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 338b44bf2274717b61b2323795a9c98f.py, line 1101, in render
  Module 338b44bf2274717b61b2323795a9c98f.py, line 911, in render_master
  Module 69e91da7ad509eec74265fa5c1df1777.py, line 1465, in render_master
  Module 69e91da7ad509eec74265fa5c1df1777.py, line 645, in render_content
  Module 338b44bf2274717b61b2323795a9c98f.py, line 901, in __fill_main
  Module 338b44bf2274717b61b2323795a9c98f.py, line 153, in render_main
  Module 5f0aa4601784b64af4844c8766340a88.py, line 414, in render_body
  Module Products.Archetypes.BaseObject, line 276, in widget
  Module Products.Archetypes.Renderer, line 26, in render
  Module Products.Archetypes.generator.widget, line 147, in __call__
AttributeError: Macro bika_widgets/remarks does not exist for <Patient at patient.2018-09-17.1793646232>