Compatibility with senaite.core 1.3 (#116)
* senaite.health profile review

* Artifact for CustomPubPrefVocabulary

* Remove old-school AnalysisRequestWorkflowAction

* Make senaite.health to compile and work with latest senaite.core

- Removal of old permissions
- Removal of sample dependencies in views
- Removal of workflowaction obsolete dependencies
- Removal of code no longer used

* Patient(s) compatibility

* Cleanup patients catalog

* ID Formatting for Patient and Doctor types

* Permissions configuration for Patient objects

Only "Owners" can edit Patients

* "Sample" action views removal, permissions and upgrade step

* Role mappings

* Batches stuff

* Setup Batch objects ownership

* Display add button in batches listing

* Health-specific columns are not displayed in Batches listings

* Add button in analysis requests base folder for Clients

* Showon=True for patient reference widgets

* Fix CustomPubPrefVocabularyFactory Traceback

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 32, in _call
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 158, in render
  Module chameleon.zpt.template, line 297, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 8bf8762ce2bde124f418b4c4c88f848b.py, line 1101, in render
  Module 8bf8762ce2bde124f418b4c4c88f848b.py, line 911, in render_master
  Module 915dfcac1f7f44dca314eeed5b1c0628.py, line 1465, in render_master
  Module 915dfcac1f7f44dca314eeed5b1c0628.py, line 645, in render_content
  Module 8bf8762ce2bde124f418b4c4c88f848b.py, line 901, in __fill_main
  Module 8bf8762ce2bde124f418b4c4c88f848b.py, line 153, in render_main
  Module e5ad07cabf4c84d028d77bc2ae4d9793.py, line 417, in render_body
  Module a17df9d39fc594cb82dcdf191148a6a1.py, line 958, in render_edit
  Module c8c5602f52731da1f57e27855df98238.py, line 564, in render_edit
  Module a17df9d39fc594cb82dcdf191148a6a1.py, line 127, in __fill_widget_body
  Module Products.Archetypes.Field, line 534, in Vocabulary
  Module zope.component._api, line 169, in getUtility
ComponentLookupError: (<InterfaceClass zope.schema.interfaces.IVocabularyFactory>, 'bika.health.obsolete.CustomPubPrefVocabularyFactory')

* Fixes #114 "Analysis Requests" --> "Samples"

* Fix #115 Do not allow the edition of patient-related fields